[tool.poetry]
name = "onkodicom"
version = "0.1.0"
description = ""
authors = ["Ashley Maher <ashley.maher@didymodesigns.com.au>"]
license = "LGPL"

[tool.poetry.dependencies]
python =  ">=3.8,<3.10" 
cython = { version = "*", optional = false }  # groups = ["user", "dev"]
numpy = { version = "*", optional = false }  # groups = ["user", "dev"]
platipy = { version = "0.2.1", optional = false }  # groups = ["user", "dev"]
alphashape = { version = "*", optional = false }  # groups = ["user", "dev"]
pandas = { version = "*", optional = false }  # groups = ["user", "dev"]
scikit-build = { version = "*", optional = false }  # groups = ["user", "dev"]
scipy = { version = "*", optional = false }  # groups = ["user", "dev"]
dicompyler-core = { version = "*", optional = false }  # groups = ["user", "dev"]
pydicom = { version = "*", optional = false }  # groups = ["user", "dev"]
country-list = { version = "*", optional = false }  # groups = ["user", "dev"]
scikit-image = { version = "*", optional = false }  # groups = ["user", "dev"]
fuzzywuzzy = { version = "*", optional = false }  # groups = ["user", "dev"]
PyWavelets = { version = "^1.1.1", optional = false }
dataclasses = { version = "^0.7", python = "~3.6" }
networkx = { version = "*", optional = false }  # groups = ["user", "dev"]
pymedphys =  { version = ">=0.35,<=0.37.1", optional = false }  # groups = ["user", "dev"]
pytest-qt = { version = ">=4.0.2", optional = false }  # groups = ["user", "dev"]
pytest = { version = "6.1.2", optional = false }  # groups = ["user", "dev"]
pyside6 = { version = "6.1.2", optional = false }  # groups = ["user", "dev"]
vtk = { version = "*", optional = false }  # groups = ["user", "dev"] 
shapely = { version = "1.8a3", optional = false }  # groups = ["user", "dev"]
python-Levenshtein = { version = "*", optional = false }  # groups = ["user", "dev"]
opencv-python = { version = "<=4.5.3.56", optional = false }  # groups = ["user", "dev"]
matplotlib = { version = "*", optional = false }  # groups = ["user", "dev"]
pyradiomics = { version = "*", optional = false }  # groups = ["user", "dev"]


[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

 
